language:
- php
- node_js
php:
- 7.1
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer install
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development-vpc
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-production-vpc
  on:
    branch: master
after_deploy:
- echo 'Successfully deployed to AWS'
env:
  global:
  - secure: WWcW6UHLAse3XQe0Jyie3XblqpPJU6udZsIwSpl3jfMgctxm+ZO2drHfvDh0NYHL/4cIJFtiUM2+XzkNHfzltg0Zm7X6tuAmhUPkoczXA8riR3LgZvvuPVif3Cw5irKy0/g/Or4Jr3WTPv+IQCbJcwwLvJt70aTCr9rlDngqs0/rHhVi4BZOv77y8LVroBrIrmwGj/Sp29M9Y1yVxAHfsOhwTXTF54EJuH/Wg90oW+teESYxJnGegnakSHXNQaWH8XaN6a4kxawpUYID/fpC5iroel+89S4B7Qcy9CiUsrJbfwk8As0QkOqqakNhsxPMN9WSDGD4odJQRKFWSt8yAN56vE6r0rPZX7ODZPbFaGRH+04aJvF43fDkQ2bC547J77L7uwur3HoVD3FW8Rueoc62xJrYthUU7GaGC9fyJEq4hE+8Q1w0ppHJLTJMv9DfSwpU8dn1RaNvn/iM2A58GXEwzPxjjdLp8huUEjHVWfKyaL7xbKAsk5xWRGiha58fKYaoMfOR6wptDmnMbfaB6RYhXwP0p7MM5nbLh4XaWTGsNbv1waAYl/8/NDD3YRo230rsBjgybgqe4TFoU3A1MJ8Q53Xwf0tbJ0sV8yQdJM/m7o1B/MGJccGC/nI+deLbdBk0OffSLEVnSsyGGX+WNex7GBL3GnhTUY8Q8Jh5WB0=
