language:
- php
- node_js
php:
- 7.1
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer install
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa-vpc
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production-vpc
  on:
    branch: master
after_deploy:
- echo 'Successfully deployed to AWS'
env:
  global:
    secure: AdFH2t7p4hzpkybm9fXrPCBYOZOh4na+geeHbd8VZlfoj7jbf82cHFUYtvjuAoI8GT6f58bOpPHL39aijSW0W1IXqEM+7g+8VBXGtksfHkjrG5G6OUhaRS1+01ZNh1O9Lp/qzX3Ec2/0sb2YuIuBR7351AiW+UgoNFKEv+6B5HdgHP/vcWwhlvoC1++soQAcFebqRY2NEeCQLL+8o/muuf7+wQG3T49oZTcgy9CpRKzCGTtOLhYYT0xn7Qs2yaSZnYzA0BeEB1G0NigQOL7ExwMdQGSZhmOGKQPDZCOQWj+vxEjAnUswIijA+choIGsBp3t7AB1BarqPhDTF+d2cMzsXXbl0Ijupt24cQbnDDrhnCq2m6dRbfKuNFW0PfmKAtWCrTze6YLm1NaLdNzVlHfMr9x658SgQviM37hsIFikLt6A6Evv1rhbFqysKqINbq3k6xYxM6SOP6TReVZrvP5IiV2behqSv2x3BF92LeYwqLKuN3qKTd/aJ9z170emFzYsLEHBXtYqkvAV9o5TT3wAQsHNK2LEYvwqEUtZvt0nLRL0Ln8A0uupbJKY86RtdHfdNSPSmTA9vPfO88YD7gtFZcZFce7msn+s25LKOX7kNJFc3sxuZsYXzdr5Y5yb7rCTQiXUadEUdNp8qfGhPGyZ8KYFvKADe3ZqGd3815Js=
