language: php
php:
  - 7.1
script:
  - composer install
  - phpunit --coverage-clover build/logs/clover.xml
after_success:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - php phpcs.phar -n --standard=PSR1,PSR2 src/
  - php vendor/bin/coveralls -v
