language:
- php
- node_js
php:
- 7.1
cache:
  directories:
  - node_modules
install:
- npm install
script:
- composer install
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa-vpc
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production-vpc
  on:
    branch: master
after_deploy:
- echo 'Successfully deployed to AWS'
env:
  global:
    secure: YWBT65i1LcnML/Drf07ni163Pu9lss2+O/+lMsn0Pt2tnLIXJxENxljR/YDQuQ0ltsLnXMifb8p1XQrxCetizDgi/2YXxMlWSBKb6hvv+abYRZPXm+QuWw5ELmYfw5nTlWILynnd8VPPlSjqKvoNqynTEJqv7Ah2W3PMUK4LovDPU+scoZdkzo3ZOOqJWnvziMqZ/Mw/Pb8O1OozxnN981i6JK+LxKIvmHn2BvPQzXYUen18tdwhfZiYdeI52q8LswoZV91W2My/8e5KKtZqq2AI1iXA4gStXUPouoasP9PuEi/f6X8uX3Ubidx0ta5EAM4tCX/pl8cIsKlEwo+VSWmberVdmMq/aCkXNG4v8XmYmuNZZ9D1HotemiW9vNMUgVIEyKBCsZqJO08ve4n/+fBQJKkZxTctHlEl8GpgrLr8ejPEDH3ZDsOppcqGul9kXLoUJWSBDJ/esmgNNn+L8W1hJXHp2yrboWUl1qTAdLM+42d2BqVMyG0rF/jyOfho8nCe9RvcErS1wfJpqwjPdovcDt9BEONTC+i/qH28EnwLrghvu9tEi9r/JrDxQoJP6nv21OUcHDPNjki99g2YDjuimLyDA1j9+jbiPpur6pmtJBGOp1L4HVA76B9e9shFiM79twR4N2a01hFqzqVpByMk7Y4WBVpGguxoTGUoJxw=
